language: go

go:
    - 1.x
    - tip

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - make getdeps

script:
  - make verifiers
  - make test
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)